# Use root/example as user/password credentials
version: '3.1'

services:

  db-mysql:
    image: mysql
    ports:
      - "3306:3306"
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: db-mysql-easyhelp
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-mysql: